backend:
  name: git-gateway
  repo: Aletay20/Souluarte
  branch: main

media_folder: "../img"          # Adjusted to go up one level from 'admin'
public_folder: "../js"          # Adjusted to go up one level from 'admin'

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "../Old_Home.html"    # Adjusted to go up one level to locate Old_Home.html
        fields:
          - { label: "Pedidos Text", name: "text_pedidos", widget: "string" }
