backend:
  name: git-gateway
  repo: Aletay20/Souluarte # Your GitHub repository
  branch: main

media_folder: "../img"       # Go up one level to access 'img' folder
public_folder: "/img"        # The public path to access images from the frontend

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "../Old_Home.html"  # Go up one level to access 'Old_Home.html' from the root
        fields:
          - { label: "Pedidos Text", name: "text_pedidos", widget: "string" }

