backend:
  name: git
  repo: aletay20/souluarte
  branch: main

media_folder: "uploads"   # Folder for storing images
public_folder: "/uploads" # Public path for images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "index"
        file: "Old_Home.html"  # Path to your homepage file
        fields:
          - { label: "Pedidos Text", name: "text_pedidos", widget: "string" }
